### ISSUE TITLE
How Knowledge graph is created

### ISSUE THREAD

**Issue by satsaras** [yankai-chen/CG-KGR#1]
Hi,
Can you help me in understanding how Knowledge graph or KG_Final.txt file is created for any of the data set?

**Comment by yankai-chen** [comment]
> Hi, Can you help me in understanding how Knowledge graph or KG_Final.txt file is created for any of the data set?

We directly use these pre-processed KGs from previous work [1,2]. 
In these papers, they say that "we use Microsoft Sotori to construct the KG for each dataset. We first select a subset of triples from the whole KG with a confidence level greater than 0.9. Given the sub-KG, we collect Satori IDs of all valid movies/books/musicians by matching their names with tail of triples (head, film.film.name, tail), (head, book.book.title, tail), or (head, type.object.name, tail). Items with multiple matched or no matched entities are excluded for simplicity. We then match the item IDs with the head of all triples and select all well-matched triples from the sub-KG. " 
Kindly check Section 4.1 in [1] for the above illustration. 

[1]  Wang, Hongwei, et al. "Knowledge graph convolutional networks for recommender systems." WWW. 2019.
[2] Wang, Hongwei, et al. "Knowledge-aware graph neural networks with label smoothness regularization for recommender systems." KDD. 2019.

**Comment by satsaras** [comment]
Thanks
